title = "order_srv"

[log]
    level = "debug"
    development = true
    disable_stacktrace = false
    encoding = "console"
    output_paths = ["logs/zap.log", "stderr"]
    error_output_paths = ["logs/err.log"]
    [log.encoder_config]
        message_key = "msg"
        level_key = "level"
        stacktrace_key = "trace"
        time_key = "ts"
        encode_level = "lowercase"
        encode_time = "iso8601"

[jwt]
    secret = "123456@#$"
    access_token_expire = -1
    refresh_token_expire = -1

[mysql]
    db_name = "byex_db_dev"
    address = "192.168.10.116:3306"
    user = "develop"
    password = "byextest456"
    table_prefix = ""
    max_open_connections = 100
    max_idle_connections = 10
    conn_max_lifetime = 0
    debug = true

[redis]
    addr = "192.168.10.240"
    password = ""
    database = 0
    idle_timeout = 20
    max_idle = 2
    max_active = 5